import React, { useRef } from 'react';
import { Download, CheckCircle, XCircle, TrendingUp, TrendingDown, Lightbulb, User, Link as LinkIcon, Star, AlertCircle } from 'lucide-react';

// Inject print CSS once into the document head
function injectPrintStyles() {
  if (document.getElementById('resume-print-styles')) return;
  const style = document.createElement('style');
  style.id = 'resume-print-styles';
  style.textContent = `
    @media print {
      body > *:not(#pdf-report-overlay) { display: none !important; }
      #pdf-report-overlay { display: block !important; position: static !important; background: white !important; }
      #pdf-report-root {
        display: block !important;
        position: static !important;
        background: white !important;
        color: #0f172a !important;
        padding: 32px !important;
        font-family: 'Segoe UI', sans-serif !important;
        font-size: 12px !important;
        line-height: 1.6 !important;
        max-width: 800px !important;
        margin: 0 auto !important;
      }
      .pdf-hide { display: none !important; }
      .pdf-section { page-break-inside: avoid; margin-bottom: 20px; }
      .pdf-chip { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; margin: 2px; border: 1px solid #ccc; }
      .pdf-chip-match { background: #d1fae5; color: #065f46; border-color: #6ee7b7; }
      .pdf-chip-miss { background: #fee2e2; color: #7f1d1d; border-color: #fca5a5; }
      .pdf-chip-neutral { background: #f1f5f9; color: #334155; border-color: #cbd5e1; }
      .pdf-score-bar-wrap { background: #e2e8f0; border-radius: 4px; height: 6px; width: 100%; }
      .pdf-score-bar-fill { height: 6px; border-radius: 4px; }
      .pdf-header { border-bottom: 2px solid #6366f1; padding-bottom: 16px; margin-bottom: 20px; }
      .pdf-section-title { font-size: 13px; font-weight: 700; color: #4f46e5; text-transform: uppercase; letter-spacing: 0.05em; border-bottom: 1px solid #e2e8f0; padding-bottom: 6px; margin-bottom: 10px; }
      .pdf-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }
      .pdf-label { color: #64748b; width: 80px; display: inline-block; }
      a { color: #4f46e5; }
    }
  `;
  document.head.appendChild(style);
}

function PdfContent({ result, filename }) {
  const { entities, match_score, matched_skills = [], missing_skills = [], llm_analysis: llm } = result;
  const hasJD = match_score !== null && match_score !== undefined;
  const hasLlm = llm && !llm.error;

  const expBadgeStyle = {
    Junior: { background: '#e0f2fe', color: '#0c4a6e', border: '1px solid #7dd3fc' },
    'Mid-Level': { background: '#fef3c7', color: '#78350f', border: '1px solid #fcd34d' },
    Senior: { background: '#d1fae5', color: '#065f46', border: '1px solid #6ee7b7' },
    'Lead/Principal': { background: '#ede9fe', color: '#3b0764', border: '1px solid #c4b5fd' },
  };

  const barColor = (v) => v >= 70 ? '#34d399' : v >= 40 ? '#fbbf24' : '#f87171';

  return (
    <div id="pdf-report-root" style={{ background: 'white', color: '#0f172a', padding: '32px', fontFamily: 'Segoe UI, sans-serif', fontSize: '13px', lineHeight: 1.6 }}>

      {/* Header */}
      <div className="pdf-header" style={{ borderBottom: '2px solid #6366f1', paddingBottom: '16px', marginBottom: '20px' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
          <div>
            <h1 style={{ fontSize: '22px', fontWeight: 800, color: '#1e1b4b', margin: 0 }}>Resume Analysis Report</h1>
            <p style={{ color: '#64748b', margin: '4px 0 0', fontSize: '12px' }}>Generated by Neural Resume Analyzer · {new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</p>
            <p style={{ color: '#64748b', margin: '2px 0 0', fontSize: '12px' }}>File: {filename}</p>
          </div>
          <div style={{ textAlign: 'right' }}>
            {hasJD && (
              <div style={{ display: 'inline-block', background: 'linear-gradient(135deg, #4f46e5, #7c3aed)', color: 'white', borderRadius: '12px', padding: '8px 20px' }}>
                <div style={{ fontSize: '28px', fontWeight: 900, lineHeight: 1 }}>{match_score}%</div>
                <div style={{ fontSize: '11px', opacity: 0.85 }}>Match Score</div>
              </div>
            )}
            {hasLlm && llm.experience_level && (
              <div style={{ marginTop: '8px' }}>
                <span style={{ ...expBadgeStyle[llm.experience_level], padding: '3px 12px', borderRadius: '20px', fontSize: '12px', fontWeight: 600 }}>
                  {llm.experience_level}
                </span>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Contact */}
      <div className="pdf-section" style={{ marginBottom: '20px' }}>
        <div className="pdf-section-title" style={{ fontSize: '11px', fontWeight: 700, color: '#4f46e5', textTransform: 'uppercase', letterSpacing: '0.05em', borderBottom: '1px solid #e2e8f0', paddingBottom: '6px', marginBottom: '10px' }}>Contact & Entities</div>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '8px', fontSize: '12px' }}>
          <div>
            <strong style={{ color: '#475569' }}>Emails</strong>
            {entities.emails.length > 0 ? entities.emails.map((e, i) => <div key={i}>{e}</div>) : <div style={{ color: '#94a3b8' }}>—</div>}
          </div>
          <div>
            <strong style={{ color: '#475569' }}>Phones</strong>
            {entities.phones.length > 0 ? entities.phones.map((p, i) => <div key={i}>{p}</div>) : <div style={{ color: '#94a3b8' }}>—</div>}
          </div>
          <div>
            <strong style={{ color: '#475569' }}>Links</strong>
            {entities.links?.length > 0 ? entities.links.map((l, i) => <div key={i}><a href={l} style={{ color: '#4f46e5', fontSize: '11px' }}>{l}</a></div>) : <div style={{ color: '#94a3b8' }}>—</div>}
          </div>
        </div>
        {entities.organizations?.length > 0 && (
          <div style={{ marginTop: '10px' }}>
            <strong style={{ color: '#475569', fontSize: '12px' }}>Organizations </strong>
            <div style={{ marginTop: '4px' }}>
              {entities.organizations.map((org, i) => <span key={i} className="pdf-chip pdf-chip-neutral" style={{ display: 'inline-block', padding: '2px 8px', borderRadius: '4px', fontSize: '11px', margin: '2px', background: '#f1f5f9', color: '#334155', border: '1px solid #cbd5e1' }}>{org}</span>)}
            </div>
          </div>
        )}
      </div>

      {/* AI Summary */}
      {hasLlm && llm.summary && (
        <div className="pdf-section" style={{ marginBottom: '20px' }}>
          <div className="pdf-section-title" style={{ fontSize: '11px', fontWeight: 700, color: '#4f46e5', textTransform: 'uppercase', letterSpacing: '0.05em', borderBottom: '1px solid #e2e8f0', paddingBottom: '6px', marginBottom: '10px' }}>AI Professional Summary</div>
          <p style={{ color: '#334155', lineHeight: 1.7, fontSize: '13px' }}>{llm.summary}</p>
        </div>
      )}

      {/* Skills */}
      <div className="pdf-section" style={{ marginBottom: '20px' }}>
        <div className="pdf-section-title" style={{ fontSize: '11px', fontWeight: 700, color: '#4f46e5', textTransform: 'uppercase', letterSpacing: '0.05em', borderBottom: '1px solid #e2e8f0', paddingBottom: '6px', marginBottom: '10px' }}>Skills Analysis</div>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
          <div>
            <strong style={{ color: '#065f46', fontSize: '12px', display: 'block', marginBottom: '6px' }}>Extracted from Resume</strong>
            {entities.skills.length > 0
              ? entities.skills.map((s, i) => <span key={i} style={{ display: 'inline-block', padding: '2px 8px', borderRadius: '4px', fontSize: '11px', margin: '2px', background: '#d1fae5', color: '#065f46', border: '1px solid #6ee7b7' }}>{s}</span>)
              : <span style={{ color: '#94a3b8' }}>None detected</span>}
          </div>
          {hasJD && (
            <div>
              <div style={{ marginBottom: '8px' }}>
                <strong style={{ color: '#065f46', fontSize: '12px', display: 'block', marginBottom: '4px' }}>Matched ({matched_skills.length})</strong>
                {matched_skills.map((s, i) => <span key={i} style={{ display: 'inline-block', padding: '2px 8px', borderRadius: '4px', fontSize: '11px', margin: '2px', background: '#d1fae5', color: '#065f46', border: '1px solid #6ee7b7' }}>{s}</span>)}
              </div>
              <div>
                <strong style={{ color: '#7f1d1d', fontSize: '12px', display: 'block', marginBottom: '4px' }}>Missing ({missing_skills.length})</strong>
                {missing_skills.length > 0
                  ? missing_skills.map((s, i) => <span key={i} style={{ display: 'inline-block', padding: '2px 8px', borderRadius: '4px', fontSize: '11px', margin: '2px', background: '#fee2e2', color: '#7f1d1d', border: '1px solid #fca5a5' }}>{s}</span>)
                  : <span style={{ color: '#065f46', fontSize: '12px' }}>No gaps — great match!</span>}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Score bars */}
      {hasJD && (
        <div className="pdf-section" style={{ marginBottom: '20px' }}>
          <div className="pdf-section-title" style={{ fontSize: '11px', fontWeight: 700, color: '#4f46e5', textTransform: 'uppercase', letterSpacing: '0.05em', borderBottom: '1px solid #e2e8f0', paddingBottom: '6px', marginBottom: '10px' }}>Fit Scores</div>
          {[
            { label: 'Skill match', value: match_score },
            hasLlm && llm.strengths ? { label: 'Strengths depth', value: Math.min(100, llm.strengths.length * 20) } : null,
            hasLlm && llm.weaknesses ? { label: 'Profile polish', value: Math.max(0, 100 - llm.weaknesses.length * 20) } : null,
          ].filter(Boolean).map((row, i) => (
            <div key={i} style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '8px', fontSize: '12px' }}>
              <span style={{ width: '110px', color: '#64748b', flexShrink: 0 }}>{row.label}</span>
              <div style={{ flex: 1, height: '6px', background: '#e2e8f0', borderRadius: '4px', overflow: 'hidden' }}>
                <div style={{ width: `${row.value}%`, height: '6px', background: barColor(row.value), borderRadius: '4px' }} />
              </div>
              <span style={{ fontWeight: 600, width: '36px', textAlign: 'right' }}>{row.value}%</span>
            </div>
          ))}
        </div>
      )}

      {/* Strengths & Weaknesses */}
      {hasLlm && (llm.strengths?.length > 0 || llm.weaknesses?.length > 0) && (
        <div className="pdf-section" style={{ marginBottom: '20px', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
          {llm.strengths?.length > 0 && (
            <div>
              <div className="pdf-section-title" style={{ fontSize: '11px', fontWeight: 700, color: '#4f46e5', textTransform: 'uppercase', letterSpacing: '0.05em', borderBottom: '1px solid #e2e8f0', paddingBottom: '6px', marginBottom: '10px' }}>Key Strengths</div>
              {llm.strengths.map((s, i) => <div key={i} style={{ display: 'flex', gap: '6px', marginBottom: '6px', fontSize: '12px', color: '#334155' }}><span style={{ color: '#10b981' }}>✦</span>{s}</div>)}
            </div>
          )}
          {llm.weaknesses?.length > 0 && (
            <div>
              <div className="pdf-section-title" style={{ fontSize: '11px', fontWeight: 700, color: '#4f46e5', textTransform: 'uppercase', letterSpacing: '0.05em', borderBottom: '1px solid #e2e8f0', paddingBottom: '6px', marginBottom: '10px' }}>Areas to Improve</div>
              {llm.weaknesses.map((w, i) => <div key={i} style={{ display: 'flex', gap: '6px', marginBottom: '6px', fontSize: '12px', color: '#334155' }}><span style={{ color: '#f43f5e' }}>✦</span>{w}</div>)}
            </div>
          )}
        </div>
      )}

      {/* Fit analysis */}
      {hasLlm && llm.fit_analysis && (
        <div className="pdf-section" style={{ marginBottom: '20px' }}>
          <div className="pdf-section-title" style={{ fontSize: '11px', fontWeight: 700, color: '#4f46e5', textTransform: 'uppercase', letterSpacing: '0.05em', borderBottom: '1px solid #e2e8f0', paddingBottom: '6px', marginBottom: '10px' }}>Job Fit Analysis</div>
          <p style={{ color: '#334155', lineHeight: 1.7, fontSize: '13px' }}>{llm.fit_analysis}</p>
        </div>
      )}

      {/* Recommendations */}
      {hasLlm && llm.recommendations?.length > 0 && (
        <div className="pdf-section" style={{ marginBottom: '20px' }}>
          <div className="pdf-section-title" style={{ fontSize: '11px', fontWeight: 700, color: '#4f46e5', textTransform: 'uppercase', letterSpacing: '0.05em', borderBottom: '1px solid #e2e8f0', paddingBottom: '6px', marginBottom: '10px' }}>Recommendations</div>
          {llm.recommendations.map((r, i) => (
            <div key={i} style={{ display: 'flex', gap: '10px', marginBottom: '8px', fontSize: '12px', color: '#334155' }}>
              <span style={{ fontWeight: 700, color: '#d97706', flexShrink: 0 }}>#{i + 1}</span>{r}
            </div>
          ))}
        </div>
      )}

      {/* Footer */}
      <div style={{ marginTop: '32px', borderTop: '1px solid #e2e8f0', paddingTop: '12px', fontSize: '11px', color: '#94a3b8', textAlign: 'center' }}>
        Neural Resume Analyzer · Hybrid NLP + LLM Engine · spaCy + OpenRouter Gemini
      </div>
    </div>
  );
}

export default function ExportReport({ result, filename, onClose }) {
  const overlayRef = useRef(null);

  const handlePrint = () => {
    injectPrintStyles();
    window.print();
  };

  return (
    <div
      id="pdf-report-overlay"
      style={{ position: 'fixed', inset: 0, zIndex: 50, background: 'rgba(2,6,23,0.85)', backdropFilter: 'blur(4px)', overflowY: 'auto', padding: '24px 16px' }}
      onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}
    >
      <div style={{ maxWidth: '760px', margin: '0 auto', position: 'relative' }}>
        {/* Toolbar */}
        <div className="pdf-hide" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
          <span style={{ color: '#94a3b8', fontSize: '13px' }}>Preview — click Export PDF to save</span>
          <div style={{ display: 'flex', gap: '10px' }}>
            <button
              onClick={onClose}
              style={{ padding: '8px 18px', borderRadius: '12px', border: '1px solid rgba(255,255,255,0.12)', background: 'transparent', color: '#94a3b8', fontSize: '13px', cursor: 'pointer' }}
            >
              Close
            </button>
            <button
              onClick={handlePrint}
              style={{ padding: '8px 20px', borderRadius: '12px', border: 'none', background: 'linear-gradient(135deg, #6366f1, #8b5cf6)', color: 'white', fontSize: '13px', fontWeight: 600, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '6px' }}
            >
              <Download size={14} /> Export PDF
            </button>
          </div>
        </div>

        {/* Report */}
        <div style={{ background: 'white', borderRadius: '16px', overflow: 'hidden', boxShadow: '0 25px 50px rgba(0,0,0,0.5)' }}>
          <PdfContent result={result} filename={filename} />
        </div>
      </div>
    </div>
  );
}
